---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Install Python3
      raw: apt-get update && apt-get install -y python3 python3-pip
      args:
        executable: /bin/bash

    - name: Create test user
      user:
        name: testuser
        shell: /bin/bash
        create_home: true
        groups: sudo
        state: present

    - name: Configure sudoers for testuser
      copy:
        content: "testuser ALL=(ALL) NOPASSWD: ALL"
        dest: /etc/sudoers.d/testuser
        mode: '0440'
        validate: /usr/sbin/visudo -cf %s
