---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Install required packages
      package:
        name:
          - python3
          - python3-pip
        state: present
      when: ansible_os_family in ['Debian', 'Ubuntu']

    - name: Create test user
      user:
        name: testuser
        shell: /bin/bash
        create_home: true
        groups: sudo
        state: present

    - name: Configure sudoers for testuser
      copy:
        content: "testuser ALL=(ALL) NOPASSWD: ALL"
        dest: /etc/sudoers.d/testuser
        mode: '0440'
        validate: /usr/sbin/visudo -cf %s 